[theme]
base = "light"
primaryColor = "#245A42"
backgroundColor = "#F5F7F3"
secondaryBackgroundColor = "#E9EFDF"
textColor = "#18332F"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
