[theme]
base = "light"
primaryColor = "#A94E32"
backgroundColor = "#F6F2EB"
secondaryBackgroundColor = "#ECE6DC"
textColor = "#202B38"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
